### ISSUE TITLE
Can not save product.

### ISSUE THREAD

**Issue by hoangnm89** [magepal/magento2-link-product#1]
### Preconditions (*)
1. Magento EE 2.2.6 with sample data

### Steps to reproduce (*)
1. Edit Product
2. Add Accessory products
3. Save

### Expected result (*)
1. Save successfully and product should have accessory products.

### Actual result (*)
1. It show message: Invalid data provided for linked products
2. No accessory product added

![image](https://user-images.githubusercontent.com/655821/49641641-558f2f00-fa43-11e8-9165-a015e872ca80.png)

**Comment by srenon** [comment]
@hoangnm89 

Update to the latest version then
1. delete 'MagePal_LinkProduct' from table 'setup_module'
2. rerun Magento setup:upgrade
