### ISSUE TITLE
Composer Not Compatible With Magento v2.4.2-p2

### ISSUE THREAD

**Issue by ryan-copeland** [magepal/magento2-link-product#10]
The extension can't be installed via composer with Magento v2.4.2-p2. See error message below:

Problem 1
    - magepal/link-product 1.1.1 requires magento/module-backend 100.0.*|100.1.*|100.2.*|101.0.0 -> found magento/module-backend[100.0.2, ..., 100.2.11, 101.0.0] but the package is fixed to 102.0.2-p2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - magepal/link-product[1.1.2, ..., 1.1.5] require magento/module-backend 100.0.*|100.1.*|100.2.*|101.0.* -> found magento/module-backend[100.0.2, ..., 100.2.11, 101.0.0, ..., 101.0.7] but the package is fixed to 102.0.2-p2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires magepal/link-product ^1.1 -> satisfiable by magepal/link-product[1.1.1, ..., 1.1.5].

**Comment by srenon** [comment]
@ryan-copeland ... sorry for the delay... please try 1.1.6
