### ISSUE TITLE
Can accessory_relations be imported in CSV import?

### ISSUE THREAD

**Issue by amenk** [magepal/magento2-link-product#2]
In which field is the import of relations done in the import? Does it work at all?

**Comment by amenk** [comment]
It does not work in the import .. working on a PR to make that work

**Comment by amenk** [comment]
Okay, fix looks very simple.

in vendor/magento/module-catalog-import-export/Model/Import/Product.php:219 we need

    protected $_linkNameToId = [
        '_related_' => \Magento\Catalog\Model\Product\Link::LINK_TYPE_RELATED,
        '_crosssell_' => \Magento\Catalog\Model\Product\Link::LINK_TYPE_CROSSSELL,
        '_upsell_' => \Magento\Catalog\Model\Product\Link::LINK_TYPE_UPSELL,
        '_accessory_' => \MagePal\LinkProduct\Model\Product\Link::LINK_TYPE_ACCESSORY,
    ];

But how to add this as a plugin without a class rewrite?

**Comment by srenon** [comment]
done
