### ISSUE TITLE
Incomplete namespace

### ISSUE THREAD

**Issue by kapil-infobeans** [magepal/magento2-link-product#5]
**File**: Plugin/CatalogImportExport/Model/Import/Product.php

Incomplete namespace: 

`use Magento\CatalogImportExport\Model\Import\Produc;`

It should be

`use Magento\CatalogImportExport\Model\Import\Product;`

It did not break because below in plugin method, As an argument it is provided with full namespace instead of alias 'Product.'

**Comment by srenon** [comment]
@kapil-infobeans ... thanks for bringing this to our attention. A new version will be release shortly
