### ISSUE TITLE
Unable to import accessory items via CSV

### ISSUE THREAD

**Issue by nagarajukensium** [magepal/magento2-link-product#7]
Thanks for providing a useful concept which was helped us lot to create a custom link type products and association. 
But we are unable to import accessory products via CSV.

The CSV format following looks like below but no luck,
*Please note I have applied patch aswell.
* in the module.xml I have added sequence than did compile so that plugin has been calling and returns the value aswell, but the still imported CSV product is not saved.

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MagePal_LinkProduct" setup_version="1.1.0">
            <sequence>
    		<module name="Magento_Catalog"/>
    		<module name="Magento_CatalogImportExport"/>
    	</sequence>
    </module>
</config>
```

sku | accessory_skus
-- |       --
AC2R5 | AC2R4

Note: I have raised a ticket on Magento stack exchange for help. Please refer the link below & advise

https://magento.stackexchange.com/questions/300095/magento-2-how-to-override-or-add-my-data-to-the-respected-member-variable

**Comment by srenon** [comment]
With zero information about what version of Magento you are using will make it next to impossible to debug or help.

**Comment by nagarajukensium** [comment]
@srenon We are using Magento 2.3.1 CE

**Comment by nagarajukensium** [comment]
@srenon Is there any solution have? Could you please advise

**Comment by amenk** [comment]
@nagarajukensium Maybe #2 helps

**Comment by amenk** [comment]
I saw you found a solution on stackexchange :)
