### ISSUE TITLE
2.4.0 Error "The stock item was unable to be saved. Please try again."

### ISSUE THREAD

**Issue by almr** [magepal/magento2-link-product#8]
Hello,

Just installed extension and facing this issue during product save.
Please update a fix.

![2 4 0-error](https://user-images.githubusercontent.com/12709266/95757068-132e7d00-0cc0-11eb-8ba9-a36d942a9f9e.png)

Thanks!

**Comment by srenon** [comment]
@almr ... it will be next to impossible to even attempt to try to debug this with the little information you provided.

I'm not able to replicate any issue in 2.4.0

![image](https://user-images.githubusercontent.com/1415141/95759330-8cee4880-0c77-11eb-99f5-fc7039410108.png)

![image](https://user-images.githubusercontent.com/1415141/95759375-9e375500-0c77-11eb-9fb5-4465e498f230.png)

![image](https://user-images.githubusercontent.com/1415141/95759498-c4f58b80-0c77-11eb-814d-31c862d23476.png)

**Comment by almr** [comment]
Thank you for quick response, just checking it if there is any conflict or issue in other extension.

**Comment by almr** [comment]
@srenon 

Issue was fixed but not related to your module. 
php bin/magento module:disable {Magento_Elasticsearch,Magento_InventoryElasticsearch,Magento_Elasticsearch6,Magento_Elasticsearch7} 
did the trick.
Please note that Elastic search module issue was on localhost, needs configuration.

Anyway, thanks for your quick assistance.
